// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParsedPage.proto

package io.ssc.trackthetrackers.commons.proto;

public final class ParsedPageProtos {
  private ParsedPageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParsedPageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string url = 1;
    /**
     * <code>required string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    // required int64 archiveTime = 2;
    /**
     * <code>required int64 archiveTime = 2;</code>
     */
    boolean hasArchiveTime();
    /**
     * <code>required int64 archiveTime = 2;</code>
     */
    long getArchiveTime();

    // repeated string scripts = 3;
    /**
     * <code>repeated string scripts = 3;</code>
     */
    java.util.List<java.lang.String>
    getScriptsList();
    /**
     * <code>repeated string scripts = 3;</code>
     */
    int getScriptsCount();
    /**
     * <code>repeated string scripts = 3;</code>
     */
    java.lang.String getScripts(int index);
    /**
     * <code>repeated string scripts = 3;</code>
     */
    com.google.protobuf.ByteString
        getScriptsBytes(int index);

    // repeated string iframes = 4;
    /**
     * <code>repeated string iframes = 4;</code>
     */
    java.util.List<java.lang.String>
    getIframesList();
    /**
     * <code>repeated string iframes = 4;</code>
     */
    int getIframesCount();
    /**
     * <code>repeated string iframes = 4;</code>
     */
    java.lang.String getIframes(int index);
    /**
     * <code>repeated string iframes = 4;</code>
     */
    com.google.protobuf.ByteString
        getIframesBytes(int index);

    // repeated string links = 5;
    /**
     * <code>repeated string links = 5;</code>
     */
    java.util.List<java.lang.String>
    getLinksList();
    /**
     * <code>repeated string links = 5;</code>
     */
    int getLinksCount();
    /**
     * <code>repeated string links = 5;</code>
     */
    java.lang.String getLinks(int index);
    /**
     * <code>repeated string links = 5;</code>
     */
    com.google.protobuf.ByteString
        getLinksBytes(int index);

    // repeated string images = 6;
    /**
     * <code>repeated string images = 6;</code>
     */
    java.util.List<java.lang.String>
    getImagesList();
    /**
     * <code>repeated string images = 6;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated string images = 6;</code>
     */
    java.lang.String getImages(int index);
    /**
     * <code>repeated string images = 6;</code>
     */
    com.google.protobuf.ByteString
        getImagesBytes(int index);
  }
  /**
   * Protobuf type {@code ParsedPage}
   */
  public static final class ParsedPage extends
      com.google.protobuf.GeneratedMessage
      implements ParsedPageOrBuilder {
    // Use ParsedPage.newBuilder() to construct.
    private ParsedPage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ParsedPage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ParsedPage defaultInstance;
    public static ParsedPage getDefaultInstance() {
      return defaultInstance;
    }

    public ParsedPage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ParsedPage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              url_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              archiveTime_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                scripts_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              scripts_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                iframes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              iframes_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                links_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              links_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                images_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              images_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          scripts_ = new com.google.protobuf.UnmodifiableLazyStringList(scripts_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          iframes_ = new com.google.protobuf.UnmodifiableLazyStringList(iframes_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          links_ = new com.google.protobuf.UnmodifiableLazyStringList(links_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(images_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.internal_static_ParsedPage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.internal_static_ParsedPage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.class, io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.Builder.class);
    }

    public static com.google.protobuf.Parser<ParsedPage> PARSER =
        new com.google.protobuf.AbstractParser<ParsedPage>() {
      public ParsedPage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParsedPage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ParsedPage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string url = 1;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>required string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 archiveTime = 2;
    public static final int ARCHIVETIME_FIELD_NUMBER = 2;
    private long archiveTime_;
    /**
     * <code>required int64 archiveTime = 2;</code>
     */
    public boolean hasArchiveTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 archiveTime = 2;</code>
     */
    public long getArchiveTime() {
      return archiveTime_;
    }

    // repeated string scripts = 3;
    public static final int SCRIPTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList scripts_;
    /**
     * <code>repeated string scripts = 3;</code>
     */
    public java.util.List<java.lang.String>
        getScriptsList() {
      return scripts_;
    }
    /**
     * <code>repeated string scripts = 3;</code>
     */
    public int getScriptsCount() {
      return scripts_.size();
    }
    /**
     * <code>repeated string scripts = 3;</code>
     */
    public java.lang.String getScripts(int index) {
      return scripts_.get(index);
    }
    /**
     * <code>repeated string scripts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getScriptsBytes(int index) {
      return scripts_.getByteString(index);
    }

    // repeated string iframes = 4;
    public static final int IFRAMES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList iframes_;
    /**
     * <code>repeated string iframes = 4;</code>
     */
    public java.util.List<java.lang.String>
        getIframesList() {
      return iframes_;
    }
    /**
     * <code>repeated string iframes = 4;</code>
     */
    public int getIframesCount() {
      return iframes_.size();
    }
    /**
     * <code>repeated string iframes = 4;</code>
     */
    public java.lang.String getIframes(int index) {
      return iframes_.get(index);
    }
    /**
     * <code>repeated string iframes = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIframesBytes(int index) {
      return iframes_.getByteString(index);
    }

    // repeated string links = 5;
    public static final int LINKS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList links_;
    /**
     * <code>repeated string links = 5;</code>
     */
    public java.util.List<java.lang.String>
        getLinksList() {
      return links_;
    }
    /**
     * <code>repeated string links = 5;</code>
     */
    public int getLinksCount() {
      return links_.size();
    }
    /**
     * <code>repeated string links = 5;</code>
     */
    public java.lang.String getLinks(int index) {
      return links_.get(index);
    }
    /**
     * <code>repeated string links = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLinksBytes(int index) {
      return links_.getByteString(index);
    }

    // repeated string images = 6;
    public static final int IMAGES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList images_;
    /**
     * <code>repeated string images = 6;</code>
     */
    public java.util.List<java.lang.String>
        getImagesList() {
      return images_;
    }
    /**
     * <code>repeated string images = 6;</code>
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 6;</code>
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 6;</code>
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }

    private void initFields() {
      url_ = "";
      archiveTime_ = 0L;
      scripts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      iframes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      links_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArchiveTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, archiveTime_);
      }
      for (int i = 0; i < scripts_.size(); i++) {
        output.writeBytes(3, scripts_.getByteString(i));
      }
      for (int i = 0; i < iframes_.size(); i++) {
        output.writeBytes(4, iframes_.getByteString(i));
      }
      for (int i = 0; i < links_.size(); i++) {
        output.writeBytes(5, links_.getByteString(i));
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeBytes(6, images_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, archiveTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < scripts_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(scripts_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getScriptsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < iframes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(iframes_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIframesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < links_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(links_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLinksList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < images_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(images_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getImagesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ParsedPage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.internal_static_ParsedPage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.internal_static_ParsedPage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.class, io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.Builder.class);
      }

      // Construct using io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        archiveTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        scripts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        iframes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        links_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.internal_static_ParsedPage_descriptor;
      }

      public io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage getDefaultInstanceForType() {
        return io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.getDefaultInstance();
      }

      public io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage build() {
        io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage buildPartial() {
        io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage result = new io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.archiveTime_ = archiveTime_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          scripts_ = new com.google.protobuf.UnmodifiableLazyStringList(
              scripts_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.scripts_ = scripts_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          iframes_ = new com.google.protobuf.UnmodifiableLazyStringList(
              iframes_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.iframes_ = iframes_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          links_ = new com.google.protobuf.UnmodifiableLazyStringList(
              links_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.links_ = links_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          images_ = new com.google.protobuf.UnmodifiableLazyStringList(
              images_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.images_ = images_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage) {
          return mergeFrom((io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage other) {
        if (other == io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasArchiveTime()) {
          setArchiveTime(other.getArchiveTime());
        }
        if (!other.scripts_.isEmpty()) {
          if (scripts_.isEmpty()) {
            scripts_ = other.scripts_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureScriptsIsMutable();
            scripts_.addAll(other.scripts_);
          }
          onChanged();
        }
        if (!other.iframes_.isEmpty()) {
          if (iframes_.isEmpty()) {
            iframes_ = other.iframes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIframesIsMutable();
            iframes_.addAll(other.iframes_);
          }
          onChanged();
        }
        if (!other.links_.isEmpty()) {
          if (links_.isEmpty()) {
            links_ = other.links_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLinksIsMutable();
            links_.addAll(other.links_);
          }
          onChanged();
        }
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasArchiveTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.ssc.trackthetrackers.commons.proto.ParsedPageProtos.ParsedPage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string url = 1;
      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      // required int64 archiveTime = 2;
      private long archiveTime_ ;
      /**
       * <code>required int64 archiveTime = 2;</code>
       */
      public boolean hasArchiveTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 archiveTime = 2;</code>
       */
      public long getArchiveTime() {
        return archiveTime_;
      }
      /**
       * <code>required int64 archiveTime = 2;</code>
       */
      public Builder setArchiveTime(long value) {
        bitField0_ |= 0x00000002;
        archiveTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 archiveTime = 2;</code>
       */
      public Builder clearArchiveTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        archiveTime_ = 0L;
        onChanged();
        return this;
      }

      // repeated string scripts = 3;
      private com.google.protobuf.LazyStringList scripts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureScriptsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          scripts_ = new com.google.protobuf.LazyStringArrayList(scripts_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public java.util.List<java.lang.String>
          getScriptsList() {
        return java.util.Collections.unmodifiableList(scripts_);
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public int getScriptsCount() {
        return scripts_.size();
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public java.lang.String getScripts(int index) {
        return scripts_.get(index);
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public com.google.protobuf.ByteString
          getScriptsBytes(int index) {
        return scripts_.getByteString(index);
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public Builder setScripts(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScriptsIsMutable();
        scripts_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public Builder addScripts(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScriptsIsMutable();
        scripts_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public Builder addAllScripts(
          java.lang.Iterable<java.lang.String> values) {
        ensureScriptsIsMutable();
        super.addAll(values, scripts_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public Builder clearScripts() {
        scripts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string scripts = 3;</code>
       */
      public Builder addScriptsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureScriptsIsMutable();
        scripts_.add(value);
        onChanged();
        return this;
      }

      // repeated string iframes = 4;
      private com.google.protobuf.LazyStringList iframes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIframesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          iframes_ = new com.google.protobuf.LazyStringArrayList(iframes_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public java.util.List<java.lang.String>
          getIframesList() {
        return java.util.Collections.unmodifiableList(iframes_);
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public int getIframesCount() {
        return iframes_.size();
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public java.lang.String getIframes(int index) {
        return iframes_.get(index);
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIframesBytes(int index) {
        return iframes_.getByteString(index);
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public Builder setIframes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIframesIsMutable();
        iframes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public Builder addIframes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIframesIsMutable();
        iframes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public Builder addAllIframes(
          java.lang.Iterable<java.lang.String> values) {
        ensureIframesIsMutable();
        super.addAll(values, iframes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public Builder clearIframes() {
        iframes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string iframes = 4;</code>
       */
      public Builder addIframesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIframesIsMutable();
        iframes_.add(value);
        onChanged();
        return this;
      }

      // repeated string links = 5;
      private com.google.protobuf.LazyStringList links_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLinksIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          links_ = new com.google.protobuf.LazyStringArrayList(links_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public java.util.List<java.lang.String>
          getLinksList() {
        return java.util.Collections.unmodifiableList(links_);
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public int getLinksCount() {
        return links_.size();
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public java.lang.String getLinks(int index) {
        return links_.get(index);
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLinksBytes(int index) {
        return links_.getByteString(index);
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public Builder setLinks(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinksIsMutable();
        links_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public Builder addLinks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinksIsMutable();
        links_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public Builder addAllLinks(
          java.lang.Iterable<java.lang.String> values) {
        ensureLinksIsMutable();
        super.addAll(values, links_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public Builder clearLinks() {
        links_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string links = 5;</code>
       */
      public Builder addLinksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinksIsMutable();
        links_.add(value);
        onChanged();
        return this;
      }

      // repeated string images = 6;
      private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          images_ = new com.google.protobuf.LazyStringArrayList(images_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public java.util.List<java.lang.String>
          getImagesList() {
        return java.util.Collections.unmodifiableList(images_);
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public int getImagesCount() {
        return images_.size();
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public java.lang.String getImages(int index) {
        return images_.get(index);
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public com.google.protobuf.ByteString
          getImagesBytes(int index) {
        return images_.getByteString(index);
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public Builder setImages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public Builder addImages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public Builder addAllImages(
          java.lang.Iterable<java.lang.String> values) {
        ensureImagesIsMutable();
        super.addAll(values, images_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public Builder clearImages() {
        images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string images = 6;</code>
       */
      public Builder addImagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
        images_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ParsedPage)
    }

    static {
      defaultInstance = new ParsedPage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ParsedPage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ParsedPage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ParsedPage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ParsedPage.proto\"o\n\nParsedPage\022\013\n\003url\030" +
      "\001 \002(\t\022\023\n\013archiveTime\030\002 \002(\003\022\017\n\007scripts\030\003 " +
      "\003(\t\022\017\n\007iframes\030\004 \003(\t\022\r\n\005links\030\005 \003(\t\022\016\n\006i" +
      "mages\030\006 \003(\tB<\n(io.ssc.trackthetrackers.e" +
      "xtraction.protoB\020ParsedPageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ParsedPage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ParsedPage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ParsedPage_descriptor,
              new java.lang.String[] { "Url", "ArchiveTime", "Scripts", "Iframes", "Links", "Images", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
